services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: financial-platform-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.2.0
    container_name: financial-platform-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:
